{{- $fullname := include "postfix-relay.fullname" . -}}
{{- $myHostName := default $fullname .Values.myHost -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "postfix-relay.fullname" . }}
data:
  RELAY_HOST: {{ required ".Values.host is required!" .Values.host | quote }}
  RELAY_MYHOSTNAME: {{ $myHostName | quote }}
  RELAY_SECURITY_OPTIONS: {{ .Values.securityOptions | quote }}
  RELAY_NETWORKS: {{ .Values.networks | quote }}
  RELAY_TLS_ENABLED: {{ if .Values.tls.enabled -}}"yes"{{- else -}}"no"{{- end }}
  RELAY_TLS_SECURITY_LEVEL: {{ .Values.tls.securityLevel | quote }}
  RELAY_TLS_STARTTLS_OFFER: {{ .Values.tls.startTlsOffer | quote }}
