apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postfix-relay.fullname" . }}
  labels:
    app: {{ include "postfix-relay.name" . }}
    chart: {{ include "postfix-relay.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  relay-username: {{ required ".Values.username is required!" .Values.username | b64enc | quote }}
  relay-password: {{ required ".Values.password is required!" .Values.password | b64enc | quote }}
