apiVersion: v1
kind: Service
metadata:
  name: {{ include "postfix-relay.fullname" . }}
  labels:
    app: {{ include "postfix-relay.name" . }}
    chart: {{ include "postfix-relay.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: smtp
      protocol: TCP
      name: smtp
  selector:
    app: {{ include "postfix-relay.name" . }}
    release: {{ .Release.Name }}
