apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "boris.configmapname" . }}
data:
  DJANGO_SETTINGS_MODULE: "boris.settings"
  BORIS_INSTALLATION: {{ template "boris.name" . }}
  BORIS_DEBUG: {{ if .Values.borisDebug -}}"1"{{- else -}}"0"{{- end }}
  BORIS_ADMIN_EMAIL: {{ .Values.borisAdminEmail | quote }}
  BORIS_EMAIL_HOST: {{ .Values.borisEmailHost | quote }}
  BORIS_ALLOWED_HOSTS: {{ .Values.borisAllowedHosts | quote }}
  BORIS_DB_HOST: {{ template "mysql.fullname" . }}
  BORIS_DB_PORT: "3306"
  BORIS_DB_NAME: {{ required ".Values.mysql.mysqlDatabase is required!" .Values.mysql.mysqlDatabase | quote }}
  BORIS_DB_USER: {{ required ".Values.mysql.mysqlUser is required!" .Values.mysql.mysqlUser | quote }}
  BORIS_WORKERS: {{ required ".Values.borisWorkers is required!" .Values.borisWorkers | quote }}
  BORIS_SENTRY_DSN: {{ .Values.borisSentry.dsn | quote }}
