apiVersion: v1
kind: Secret
metadata:
  name: {{ include "boris.fullname" . }}
  labels:
    app: {{ include "boris.name" . }}
    chart: {{ include "boris.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.borisSecretKey }}
  boris-secret-key:  {{ .Values.borisSecretKey | b64enc | quote }}
  {{ else }}
  boris-secret-key: {{ randAlphaNum 60 | b64enc | quote }}
  {{ end }}
