apiVersion: v1
kind: Secret
metadata:
  name: {{ include "restic-secret.fullname" . }}
  labels:
    app: {{ include "restic-secret.name" . }}
    chart: {{ include "restic-secret.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ required ".Values.name is requried" .Values.name }}: {{ if .Values.password -}}{{ .Values.password | b64enc | quote }}{{- else }}{{ randAlphaNum 10 | b64enc | quote }}{{ end }}
