apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "adv-celery.fullname" . }}
  labels:
    app: {{ include "adv-celery.name" . }}
    chart: {{ include "adv-celery.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "adv-celery.name" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name }}
      heritage: "{{ .Release.Service }}"
  template:
    metadata:
      labels:
        app: {{ include "adv-celery.name" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        heritage: "{{ .Release.Service }}"
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.pullSecretName }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command: ["celery-runner"]
          args: ['{{ required ".Values.mode is required!" .Values.mode }}']
          envFrom:
            - configMapRef:
                name: {{ include "adventura.configmapname" . | quote }}
            - secretRef:
                name: {{ include "adventura.secretname" . | quote }}
          env:
            - name: ADV_DEBUG
              value: {{ if .Values.debugMode -}}"1"{{- else -}}"0"{{- end }}
            - name: ADV_MANAGERS
              value: {{ toJson .Values.managers | quote }}
            {{ if .Values.sentry.dsn -}}
            - name: ADV_SENTRY_DSN
              value: {{ .Values.sentry.dsn | quote }}
            {{- end }}
          {{- /* no probes for beat mode yet :( */ -}}
          {{ if eq .Values.mode "worker" }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec celery -A adv.celeryconf inspect ping -d celery@$HOSTNAME
            initialDelaySeconds: 30
            timeoutSeconds: 40
            periodSeconds: 180
          {{ end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
