apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "foster.configmapname" . }}
data:
  DJANGO_SETTINGS_MODULE: "foster.settings"
  FOSTER_DEBUG: {{ if .Values.fosterDebug -}}"1"{{- else -}}"0"{{- end }}
  FOSTER_INSTALLATION: {{ template "foster.name" . }}
  FOSTER_ALLOWED_HOSTS: {{ .Values.fosterAllowedHosts | quote }}
  FOSTER_MEDIA_URL: {{ required ".Values.fosterMediaProxy.rootPath is required!" .Values.fosterMediaProxy.rootPath | quote }}
  FOSTER_SENDFILE_URL: {{ required ".Values.fosterMediaProxy.protectedPath is required!" .Values.fosterMediaProxy.protectedPath | quote }}
  FOSTER_ADMIN_EMAIL: {{ .Values.fosterAdminEmail | quote }}
  FOSTER_LANG: {{ .Values.fosterLang | quote }}
  FOSTER_TRANSFERS_HOST: {{ .Values.fosterTransfersHost | quote }}
  FOSTER_TRANSFERS_CODE: {{ .Values.fosterTransfersCode | quote }}
  FOSTER_POSTGRES_HOST: {{ template "postgresql.fullname" . }}
  FOSTER_POSTGRES_DBNAME: {{ required ".Values.postgresql.postgresDatabase is required!" .Values.postgresql.postgresDatabase | quote }}
  FOSTER_POSTGRES_USER: {{ required ".Values.postgresql.postgresUser is required!" .Values.postgresql.postgresUser | quote }}
  FOSTER_WORKERS: {{ required ".Values.fosterWorkers is required!" .Values.fosterWorkers | quote }}
  FOSTER_SENTRY_DSN: {{ .Values.fosterSentry.dsn | quote }}
  FOSTER_SECURE_COOKIE: {{ if and .Values.ingress.enabled  .Values.ingress.createTls -}}"1"{{- else -}}"0"{{- end }}
