apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "foster.dbinitjobname" . }}
  labels:
    app: {{ include "foster.name" . }}
    jobname: db-init
    # The "app.kubernetes.io/managed-by" label is used to track which tool deployed a given chart.
    # It is useful for admins who want to see what releases a particular tool
    # is responsible for.
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    # The "app.kubernetes.io/instance" convention makes it easy to tie a release to all of the
    # Kubernetes resources that were created as part of that release.
    app.kubernetes.io/instance: {{ .Release.Name }}
    # This makes it easy to audit chart usage.
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      initContainers:
        # Wait for database to be ready before attempting the migration.
        - name: {{ printf "%s-wait-for-database" .Chart.Name }}
          image: "groundnuty/k8s-wait-for:v1.1"
          imagePullPolicy: Always
          command: ["sh", '-c', 'wait_for.sh pod -lapp={{ include "postgresql.name" . }} && sleep 10']
      containers:
        - name: main
          image: "{{ required ".Values.image.repository is required!" .Values.image.repository }}:{{ required ".Values.image.tag is required!" .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # Sleep for few seconds so that PostgreSQL intializes
          command: ['/foster/bin/db-init.sh']
          envFrom:
            - configMapRef:
                name: {{ template "foster.configmapname" . }}
          env:
            - name: FOSTER_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "postgresql.fullname" . }}
                  key: postgres-password
            - name: FOSTER_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "foster.fullname" . }}
                  key: foster-secret-key
      restartPolicy: Never
  backoffLimit: 5
