apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "proxy.fullname" . }}
  labels:
    app: {{ template "proxy.name" . }}
    chart: {{ include "foster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  default.conf: |-
    server {
      listen       {{ .Values.fosterMediaProxy.service.port }};

      location /probe {
          return 200 'OK';
      }

      # Auth-protected files work using X-Accel header
      location {{ .Values.fosterMediaProxy.protectedPath }} {
          internal;
          alias /foster-media;
      }

      location / {
        # Foward requests for foster app
        resolver kube-dns.kube-system.svc.cluster.local valid=5s;
        set $service "{{ template "foster.fullname" . }}";
        proxy_pass "http://$service.{{ .Release.Namespace }}.svc.cluster.local";
      }

      #error_page  404              /404.html;

      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }

