apiVersion: v1
kind: Service
metadata:
  name: {{ template "proxy.fullname" . }}
  labels:
    app: {{ template "proxy.name" . }}
    chart: {{ include "foster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.fosterMediaProxy.service.type }}
  ports:
  - name: http
    port: {{ .Values.fosterMediaProxy.service.port }}
    targetPort: http
  selector:
    app: {{ template "proxy.name" . }}
    release: {{ .Release.Name }}
