apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "adv-web.fullname" . }}
  labels:
    app: {{ include "adv-web.name" . }}
    chart: {{ include "adv-web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "adv-web.name" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name }}
      heritage: "{{ .Release.Service }}"
  template:
    metadata:
      labels:
        app: {{ include "adv-web.name" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        heritage: "{{ .Release.Service }}"
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.pullSecretName }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "adventura.configmapname" . | quote }}
            - secretRef:
                name: {{ include "adventura.secretname" . | quote }}
          env:
            - name: ADV_WORKERS
              value: {{ .Values.workers | quote }}
            - name: ADV_WORKER_TIMEOUT
              value: "100"
            - name: ADV_WORKER_CLASS
              value: "sync"
            - name: ADV_WORKER_NAME
              value: {{ .Values.workerName | quote }}
            - name: ADV_DEBUG
              value: {{ if .Values.debugMode -}}"1"{{- else -}}"0"{{- end }}
            - name: ADV_MANAGERS
              value: {{ toJson .Values.managers | quote }}
            - name: ADV_WEB_ROOT_URL
              value: {{ (index .Values.ingress.hosts 0).host | quote }}
            {{ if .Values.cloudfrontDomain -}}
            - name: ADV_AWS_PUBLIC_S3_CUSTOM_DOMAIN
              value: {{ .Values.cloudfrontDomain | quote }}
            {{- end }}
            - name: DJANGO_SETTINGS_MODULE
              value: {{ .Values.settingsModule | quote }}
            {{ if .Values.sentry.dsn -}}
            - name: ADV_SENTRY_DSN
              value: {{ .Values.sentry.dsn | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness-probe/
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /liveness-probe/
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 5
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
