apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "fcp.fullname" . }}
  labels:
    app: {{ include "fcp.name" . }}
    chart: {{ include "fcp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "fcp.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "fcp.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ template "fcp.configmapname" . }}
          env:
            - name: FOSTER_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "postgresql.fullname" . }}
                  key: postgres-password
            - name: FOSTER_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fcp.fullname" . }}
                  key: fcp-secret-key
          ports:
            - name: http
              containerPort: {{ required ".Values.fcpPort is required!" .Values.fcpPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /admin/
              port: http
          readinessProbe:
            httpGet:
              path: /admin/
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
