apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fcp.fullname" . }}
  labels:
    app: {{ include "fcp.name" . }}
    chart: {{ include "fcp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.fcpSecretKey }}
  fcp-secret-key:  {{ .Values.fcpSecretKey | b64enc | quote }}
  {{ else }}
  fcp-secret-key: {{ randAlphaNum 60 | b64enc | quote }}
  {{ end }}
