apiVersion: v1
kind: Service
metadata:
  name: {{ include "fcp.fullname" . }}
  labels:
    app: {{ include "fcp.name" . }}
    chart: {{ include "fcp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ required ".Values.service.port is required!" .Values.service.port }}
      targetPort: {{ required ".Values.fcpPort is required!" .Values.fcpPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "fcp.name" . }}
    release: {{ .Release.Name }}
