apiVersion: v1
appVersion: "0.1.3"
description: A Helm chart for Kubernetes to deploy Foster central point installation
name: foster-centralpoint
version: 0.1.5
icon: https://svpfrydlant.foster.f-app.it/static/images/foster_logo_resize.61f314ae8dd3.png
