# Default values for fcp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker-registry.f-app.it/fcp
  tag: 0.1.2
  pullPolicy: IfNotPresent
  pullSecretName: fragaria-private

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts: []
    # - name: default
    #   host: installation.bor-is.cz
  createTls: true

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

# fcp specific settings.
fcpPort: 8000
fcpDebug: false
fcpAdminEmail: "admin@fragaria.cz"
fcpWorkers: 1
fcpAllowedHosts: "*"
fcpSecretKey: ""
fcpCreateSuperUser: false
fcpSuperUserUsername: "admin"
fcpSuperUserEmail: "admin@fragaria.cz"
fcpSuperUserPassword: ""
fcpBackup:
  enabled: false
  schedule: "0 4 * * *"
fcpSentry:
  dsn: ""

postgresql:
  postgresDatabase: fcp
  postgresPassword: fcp
  postgresUser: fcp

  ## Persist data to a persistent volume
  persistence:
    enabled: true
    ## database data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 2Gi
    annotations: {}
    resourcePolicy: ""

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

    limits:
      cpu: 500m
      memory: 256Mi

  probes:
    liveness:
      initialDelay: 120
    readiness:
      initialDelay: 20
