{{- define "adv-web.haystackconn" -}}
{"default": {"ENGINE": "adv.app.es.ExtElasticsearchSearchEngine", "URL": "{{ required '.Values.elasticsearch.host is required!' .Values.elasticsearch.host }}:{{ default values.elasticsearch.port 9200 }}", "INDEX_NAME": "adventura"}, "cht": {"ENGINE": "adv.app.es.ExtElasticsearchSearchEngine", "URL": "{{ required '.Values.elasticsearch.host is required!' values.elasticsearch.host }}:{{ default values.elasticsearch.port 9200 }}", "INDEX_NAME": "chinatours"}}
{{- end -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "adv-web.configmapname" . }}
data:
  ADV_WORKERS: {{ default .Values.workers 1 }}
  ADV_SECRET: {{ .Values.secretKey | quote }}
  ADV_DEBUG: {{ if .Values.debugMode -}}"1"{{- else -}}"0"{{- end }}
  ADV_WEB_API_SALT: {{ .Values.signSalt }}
  DJANGO_SETTINGS_MODULE: {{ .Values.settingsModule }}
  DB_USER: {{ required ".Values.db.user is required!" .Values.db.user | quote }}
  DB_NAME: {{ required ".Values.db.name is required!" .Values.db.name | quote }}
  DB_PASSWORD: {{ required ".Values.db.password is required!" .Values.db.password | quote }}
  DB_HOST: {{ required ".Values.db.host is required!" .Values.db.host | quote }}
  REDIS_HOST: {{ required ".Values.redis.host is required!" .Values.redis.host | quote }}
  ADV_CONSTANCE_BACKEND: {{ required ".Values.constance.backend is required!" .Values.constance.backend | quote }}
  ADV_DEFAULT_FROM_EMAIL: {{ required ".Values.defaultFromEmail is required!" .Values.defaultFromEmail | quote }}
  ADV_MANAGERS: {{ toJson .Values.managers | quote }}
  {{ if .Values.ingress.enabled }}
  ADV_WEB_ROOT_URL: {{ .Values.ingress.hosts[0] }}
  {{ end }}
  ADV_CLM_API_ADV_HOST: {{ required ".Values.clm.adv.host is required!" .Values.clm.adv.host | quote }}
  ADV_CLM_API_ADV_SECRET: {{ required ".Values.clm.adv.secret is required!" .Values.clm.adv.secret | quote }}
  ADV_CLM_API_CHT_HOST: {{ required ".Values.clm.cht.host is required!".Values.clm.cht.host | quote }}
  ADV_CLM_API_CHT_SECRET: {{ required ".Values.clm.cht.secret is required!".Values.clm.cht.secret | quote }}
  ADV_REDIS_CONSTANCE_DB: {{ default .Values.redis.databases.constance 1 }}
  ADV_REDIS_CELERYRESULTBACKEND_DB: {{ default .Values.redis.databases.celeryResult 2 }}
  ADV_REDIS_CELERYBROKER_DB: {{ default .Values.redis.databases.celeryBroker 3 }}
  ADV_REDIS_CACHE_DB: {{ default .Values.redis.databases.cache 15 }}
  ADV_HAYSTACK_CONNECTIONS: {{ include "adv-web.haystackconn" . | quote }}
  {{ if .Values.aws.enabled }}
  ADV_AWS_ENABLED: {{ if .Values.aws.enabled -}}"1"{{- else -}}"0"{{- end }}
  ADV_AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId | quote }}
  ADV_AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | quote }}
  ADV_AWS_STORAGE_BUCKET_NAME: {{ .Values.aws.bucketName | quote }}
  ADV_AWS_S3_HOST: {{ .Values.aws.s3Host | quote }}
  ADV_AWS_S3_URL_PROTOCOL: {{ .Values.aws.s3Proto | quote }}
  {{ end }}
  ADV_DISQUS_API_KEY: {{ .Values.diqus.apiKey | quote }}
  ADV_DISQUS_API_SECRET: {{ .Values.diqus.apiSecret | quote }}
  ADV_DISQUS_WEBSITE_SHORTNAME: {{ .Values.diqus.websiteShortname | quote }}
  {{ if .Values.sentry.dsn }}
  ADV_SENTRY_DSN: {{ .Values.sentry.dsn | quote }}
  {{ end }}
