apiVersion: v1
kind: Service
metadata:
  name: {{ include "adv-web.fullname" . }}-upload
  labels:
    app: {{ include "adv-web.name" . }}-upload
    chart: {{ include "adv-web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "adv-web.name" . }}-upload
    release: {{ .Release.Name }}
