apiVersion: v1
kind: Secret
metadata:
  name: {{ template "adventura.secretname" . }}
  labels:
    app: {{ include "adventura.name" . }}
    chart: {{ include "adventura.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  ADV_AWS_ACCESS_KEY_ID: {{ required ".Values.aws.accessKeyId is required!" .Values.aws.accessKeyId | b64enc | quote }}
  ADV_AWS_SECRET_ACCESS_KEY: {{ required ".Values.aws.secretAccessKey is required!" .Values.aws.secretAccessKey | b64enc | quote }}
  ADV_CLM_API_ADV_SECRET: {{ required ".Values.clm.adv.secret is required!" .Values.clm.adv.secret | b64enc | quote }}
  ADV_CLM_API_CHT_SECRET: {{ required ".Values.clm.cht.secret is required!" .Values.clm.cht.secret | b64enc | quote }}
  ADV_DISQUS_API_KEY: {{ required ".Values.disqus.apiKey is required!" .Values.disqus.apiKey | b64enc | quote }}
  ADV_DISQUS_API_SECRET: {{ required ".Values.disqus.apiSecret is required!" .Values.disqus.apiSecret | b64enc | quote }}
  ADV_POSTAGEAPP_APIKEY: {{ required ".Values.postageApp.apiKey is required!" .Values.postageApp.apiKey | b64enc | quote }}
  ADV_SECRET: {{ required ".Values.secret is required!" .Values.secret | b64enc | quote }}
  ADV_WEB_API_SALT: {{ required ".Values.webApiSalt is required!" .Values.webApiSalt | b64enc | quote }}
  DB_PASSWORD: {{ required ".Values.postgresql.postgresPassword is required!" .Values.postgresql.postgresPassword | b64enc | quote }}
