{{- if .Values.ingress.enabled -}}
{{- $fullName := include "adv-zanet.fullname" . -}}
{{- $name := include "adv-zanet.name" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-gevent
  labels:
    app: {{ $name }}
    chart: {{ include "adv-zanet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.org/proxy-read-timeout: "600s"
    nginx.org/client-max-body-size: "300M"
spec:
{{- if .Values.ingress.createTls }}
  tls:
  {{- range .Values.ingress.hosts }}
    - hosts:
        - {{ .host | quote }}
      secretName: {{ $name }}-{{ default "default" .name }}-tls
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: "/api/v1/tours/mass-make-archive-versions"
            backend:
              serviceName: {{ $fullName }}-upload
              servicePort: http
          - path: "/api/v1/photos"
            backend:
              serviceName: {{ $fullName }}-upload
              servicePort: http
          - path: "/api/v1/photo-collections"
            backend:
              serviceName: {{ $fullName }}-upload
              servicePort: http
          - path: "/admin/app/downloadablefile/add"
            backend:
              serviceName: {{ $fullName }}-upload
              servicePort: http
  {{- end }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-sync
  labels:
    app: {{ $name }}
    chart: {{ include "adv-zanet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.createTls }}
  tls:
  {{- range .Values.ingress.hosts }}
    - hosts:
        - {{ .host | quote }}
      secretName: {{ $name }}-{{ default "default" .name }}-tls
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ $fullName }}-main
              servicePort: http
  {{- end }}
{{- end }}
