apiVersion: v1
description: Sentry is a cross-platform crash reporting and aggregation platform.
name: sentry
version: 0.1.7
appVersion: 9.0
keywords:
  - debugging
  - logging
  - monitoring
sources:
  - https://github.com/getsentry/sentry
home: https://sentry.io/
icon: https://sentry-brand.storage.googleapis.com/sentry-logo-black.png
